### ISSUE TITLE
Align with open source checklist

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-dapp-kit#63]
The following confluence page has a open source checklist of tasks / items that should be complete / present on the repo before making it a public open source repo.

Tasks: 

- [x] See and align with the open source check list

Acceptance Criteria:

- [x] Alignment with each of the open source check list items
- [x] Review by PO 

Links:

-  https://vechain.atlassian.net/wiki/spaces/TestEngine/pages/261029889/Open+Source+Preparation+Checklist
